#!/bin/bash

ROUNDS=$1
STOR=$2

exec 3<> /tmp/memory-c223-$STOR

echo "0 containers:" >&3
free >&3
echo >&3

for ((outer=0; outer<$ROUNDS; outer++))
do
	for ((inner=1; inner<=63; inner++))
	do
		docker run -d --rm --net=none --cpuset-cpus="$inner" -v /root/persistent/scripts:/scripts fschmidt/micropython "/scripts/sleep.py" 1>/dev/null 2>&3
		CONT=$((outer*63+inner))
		echo "$CONT containers:" >&3
		free >&3
		df -T | head -n 16 >&3
		echo >&3
	done
done

exec 3>&-

